import Header from "@/components/Header";
import AppProviders from "@/app/AppProviders";
import "@scss/_global.scss";
import { Roboto } from "next/font/google";
import ChatbotProvider from "@/components/Chatbot";

export const metadata = {
  title: "renTalk",
  description: "Generated by Next.js",
};

const roboto = Roboto({
  subsets: ["latin", "vietnamese"],
  weight: ["100", "300", "400", "500", "700", "900"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={roboto.className}>
        <AppProviders>
          <ChatbotProvider>
            <Header />
            {children}
          </ChatbotProvider>
        </AppProviders>
      </body>
    </html>
  );
}
